data/domainExceptionPopup.js
=> more AMO fixes

data/vex/vex.css
=> remove unnecessary non-Firefox rules & properties

lib/contentPolicy.js, lib/prefsListener.js, lib/userStorage.js, test/httpd.js, test/request-base.js, test/test-cookieblock.js, test/test-dnt.js, test/test-heuristic-blocker.js, test/test-main.js, test/test-utils.js
=> Fix all the tests!

data/popup.js, lib/contentPolicy.js, lib/main.js, lib/prefsListener.js, lib/userStorage.js, test/test-private-browsing.js
=> Fix things up for submission to AMO

lib/main.js, package.json
cc @jsha @swartzcr for review.
=> make counter optional

package.json, test/test-utils.js
Merging TBR, cc @SwartzCr @jsha for review.
=> Test for shasum

LICENSE, lib/sha1.js
=> Replace nonfree SHA1 code with Mozilla API

lib/utils.js
@SwartzCr can you test this with iceweasle?
=> fix gbrowser errors. fixes #376

data/options.js, data/skin/popup.css
=> improvements to the options page. fixes #374

data/options.html, data/skin/popup.css, lib/ui.js
=> Fix the undo button

CREDITS, LICENSE
- Work by individual EFF staff is work-for-hire
- But there should be a separate CREDITS file to actually credit people :)
=> Fix licensing & credits

data/skin/firstRun.css
Minor style tweaks for first run page, merging TBR
cc @SwartzCr for review.
=> style tweaks

data/firstRun.js
Adds keyboard navigation to carousel added in #96.
=> Add keyboard controls for the carousel on the firstRun page.

lib/domainExceptions.js, lib/main.js
=> checks for tab going away. fixes #422

data/popup.js
a change that prevents people from spamming the error reporting DB and filling it with junk
=> change to prevent multiple error reports

data/options.js
was missing the _reverseSort fxn
=> fixed options page sorting

data/popup.html, data/popup.js, data/skin/popup.css
=> add loading dialog, fixes #432

data/options.js
=> full height list of domains, fixes #431

data/popup.js, lib/contentPolicy.js, lib/ui.js
fixed issue where local storage wasn't being set on pop-up load, added a wait and a prompt when a parent setting gets updated
also moved around a few rules so parent domains wouldn't override child ones
=> etld and filter overide solution

data/firstRun.js, data/firstRunCS.js, data/options.js, data/popup.js, data/skin/popup.css, lib/main.js, lib/ui.js, lib/userStorage.js, package.json
Fixes #457 
Fixes #458 
Fixes #464 
The popup was trying to access a flag in localStorage which was causing myriad problems for users that had localStorage turned off. This patch set fixes all of those problems. 
cc @jsha for review.
=> Local storage disabled bugfixes. 

.travis.yml, data/firstRun.html, package.json, prefs.json, test/test-content-policy.js, test/test-cookieblock.js, test/test-dnt.js, test/test-domain-exceptions.js, test/test-heuristic-blocker.js, test/test-main.js, test/test-preloads.js, test/test-private-browsing.js, test/test-utils.js
Setting up the repo to use jpm instead of cfx.
=> prepare for jpm

data/options.js
=> cache origins and only update changed origin, fixes #465

README.md
=> update readme. fixes #621

data/popup.js, data/skin/popup.css
Adds text-align:left so when text overflows starts on right side
This is all in reference to issue #530
=> Fixes text alignment of notracking

lib/policyCheck.js
cc @jsha or @SwartzCr for review. Some linting and removes a privacy leaking console.log call.
=> remove info leaking console log, fixes #680

lib/ui.js
cc @jsha or @SwartzCr for review.
=> badge counter only ever increases. Fixes #666

lib/contentPolicy.js, lib/utils.js, test/test-utils.js
This is in reference to issues #596 and #682. Let me know if there are any problems with this or any changes you'd like to see.
=> Whitelist private hosts

defaults/prefs.js, lib/main.js
PR for https://github.com/EFForg/privacybadgerfirefox/issues/698
=> Option to disable the firstrun page

data/socialwidgets.js
Pull request for [#701](https://github.com/EFForg/privacybadgerfirefox/issues/701)
=> Added the alt attribute to the replacement button

lib/utils.js, test/test-utils.js
This change whitelists 127.0.0.0/8 addresses instead of only 127.0.0.1.
=> Fix localhost whitelisting

data/options.html
Removed leftover Adblock Plus comment mentioned in issue #466.
=> Remove Adblock Plus comment from options.html

data/options.js
This updates the option page refresh to update the tracking domain count and list of domains without reloading the entire page.
Previously the entire page was reloaded which was pretty disruptive, but it also only updated the domain count and currently displayed tracking domains. If there were any new tracking domains found since the last refresh they didn't get displayed. This also avoids having the page reload and defaulting to the *Filter Settings* tab even if you were on the *Whitelisted Domains* or *Other Settings* tabs.
These are some of the possibly related issues I could find but I wasn't able to replicate any of them to verify: 
- #643 (one of the comments mentions the page refreshing repeatedly)
- #714 (not sure if this is because of the page reloading)
=> Refactor refresh of options page

data/options.js
In response to #745 this checks to see if any search text has been entered when the options page is being refreshed:
- If so, only the display for filtered domains is updated to show any changes for a domain.
- If not, the entire list is updated so new domains get included.
This should make the experience a bit smoother.
=> Avoid resetting filtered list on options refresh

data/popup.js, lib/domainExceptions.js
cc @SwartzCr @jsha or @Hainish. This is an urgent fix. Needs to go out today!
=> fix nonexistent api
